const CACHE_NAME='otg-v6.0.69-fh5-perf-pwa-icon';
const ASSETS=[
  './style-fh5-v6069-main.css?v=6069',
  './js/fh5-catalogue-v6069-main.js?v=6069',
  './',
  './index.html',
  './style-v5782.css?v=5782',
  './manifest.webmanifest?v=6069',
  './favicon.png',
  './js/seed-data.js?v=5780',
  './js/core.js?v=5780',
  './js/race-director.js?v=5780',
  './js/views.js?v=5780',
  './js/celebrations.js?v=5780',
  './js/garage.js?v=5780',
  './js/control-centre.js?v=5780',
  './js/studio-final-v5780.js?v=5780',
  './js/studio-locked-ui-v5780.js?v=5780',
  './js/studio-polish-v5782.js?v=5782',
  './js/bootstrap-v5782.js?v=5782',
  './assets/brand/otg-mark-painted-wall.svg',
  './assets/final/dashboard-background.png',
  './assets/final/festival-background.png',
  './assets/final/events-background.png',
  './assets/final/settings-background.png',
  './assets/final/records-background-v5744.png',
  './assets/final/hall-of-fame-background-v5744.png',
  './assets/final/settings-background-v5744.png',
  './assets/final/stats-background.png',
  './assets/final/championship-background.png',
  './assets/final/hubs.png',
  './assets/final/post-race-finish-background-v5780.png',
  './assets/final/enter-result-finish-line-hero-v5781.png',
  './assets/final/trophy-festival.png',
  './assets/final/trophy-manufacturer.png',
  './assets/final/trophy-era.png',
  './assets/final/trophy-favourite.png',
  './icons/icon-v6069-192.png',
  './icons/icon-v6069-512.png',
  './icons/icon-maskable-v6069-192.png',
  './icons/icon-maskable-v6069-512.png'
];
self.addEventListener('install',event=>{
  event.waitUntil(caches.open(CACHE_NAME).then(cache=>cache.addAll(ASSETS)));
  self.skipWaiting();
});
self.addEventListener('activate',event=>{
  event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith('racehub-')&&key!==CACHE_NAME).map(key=>caches.delete(key)))));
  self.clients.claim();
});
self.addEventListener('fetch',event=>{
  if(event.request.mode==='navigate'){
    event.respondWith(fetch(event.request,{cache:'no-store'}).catch(()=>caches.match('./index.html')));
    return;
  }
  event.respondWith(fetch(event.request,{cache:'no-store'}).then(response=>{
    const copy=response.clone();
    caches.open(CACHE_NAME).then(cache=>cache.put(event.request,copy)).catch(()=>{});
    return response;
  }).catch(()=>caches.match(event.request)));
});
